### ISSUE TITLE
Arabic ک character

### ISSUE THREAD

**Issue by d7coders** [slashmili/php-gd-persian#2]
Hi, when I'm trying to use 'ک' the script give me 'ك'

**Comment by slashmili** [comment]
@d7coders maybe it's because of this https://github.com/slashmili/php-gd-persian/blob/master/phpgd/fagd.php#L50 
can you change it and see if it works?

**Comment by mygandolf** [comment]
Oh Yes ! It Work Finally ... Thank You
and a question ... this program only work with Nastaligh.ttf or Not ?

**Comment by slashmili** [comment]
@mygandolf can you make a PR to fix it?

Not really, you can just change the font by providing font file to the function
for example look at https://github.com/slashmili/php-gd-persian/blob/master/phpgd/test01.php#L24
